import type { FallbackTopicSeed } from "./types";

/**
 * Prepared topics. Open the site with `?id=` set to one of these ids, then press start to get that topic.
 * Add `speed=2x` or `speed=3x` on the homepage to speed up the research clock,
 * with the first and last 15 seconds at real time.
 */
export const FALLBACK_SEEDS: FallbackTopicSeed[] = [
	// Bilim
	{ id: "fermi-paradoksu", title: "Fermi Paradoksu", category: "bilim" },
	{ id: "evren-neden-genisliyor", title: "Evren neden genişliyor?", category: "bilim" },
	{ id: "evrenin-bir-merkezi-var-mi", title: "Evrenin bir merkezi var mı?", category: "bilim" },
	{ id: "kara-deliklerin-icinde-ne-var", title: "Kara deliklerin içinde ne var?", category: "bilim" },
	{ id: "kara-delikler-nasil-olusur", title: "Kara delikler nasıl oluşur?", category: "bilim" },
	{ id: "kara-delikler-nasil-buharlasir", title: "Kara delikler nasıl buharlaşır?", category: "bilim" },
	{ id: "isik-hizi-neden-aslamaz", title: "Işık hızı neden aşılamaz?", category: "bilim" },
	{ id: "isik-hem-dalga-hem-parcacik-nasil-olabilir", title: "Işık hem dalga hem parçacık nasıl olabilir?", category: "bilim" },
	{ id: "zaman-neden-tek-yonde-akar", title: "Zaman neden tek yönde akar?", category: "bilim" },
	{ id: "yercekimi-zamani-nasil-yavaslatir", title: "Yerçekimi zamanı nasıl yavaşlatır?", category: "bilim" },
	{ id: "ikizler-paradoksu", title: "İkizler paradoksu nedir?", category: "bilim" },
	{ id: "schrodingerin-kedisi", title: "Schrödinger'in kedisi ne anlatır?", category: "bilim" },
	{ id: "kuantum-dolaniklik-nedir", title: "Kuantum dolanıklık nedir?", category: "bilim" },
	{ id: "kuantum-tunelleme-nedir", title: "Kuantum tünelleme nedir?", category: "bilim" },
	{ id: "belirsizlik-ilkesi-nedir", title: "Belirsizlik ilkesi nedir?", category: "bilim" },
	{ id: "madde-neden-cogunlukla-bosluktur", title: "Madde neden çoğunlukla boşluktur?", category: "bilim" },
	{ id: "atomlar-neden-birbirinin-icinden-gecmez", title: "Atomlar neden birbirinin içinden geçmez?", category: "bilim" },
	{ id: "antimadde-nedir", title: "Antimadde nedir?", category: "bilim" },
	{ id: "karanlik-madde-nedir", title: "Karanlık madde nedir?", category: "bilim" },
	{ id: "karanlik-enerji-nedir", title: "Karanlık enerji nedir?", category: "bilim" },
	{ id: "buyuk-patlamadan-once-ne-vardi", title: "Büyük Patlama'dan önce ne vardı?", category: "bilim" },
	{ id: "evren-nasil-sona-erebilir", title: "Evren nasıl sona erebilir?", category: "bilim" },
	{ id: "neden-gece-gokyuzu-karanlik", title: "Gece gökyüzü neden karanlık?", category: "bilim" },
	{ id: "gunes-nasil-milyarlarca-yildir-yaniyor", title: "Güneş nasıl milyarlarca yıldır yanıyor?", category: "bilim" },
	{ id: "yildizlar-neden-farkli-renklerde", title: "Yıldızlar neden farklı renklerde?", category: "bilim" },
	{ id: "supernova-nedir", title: "Süpernova nedir?", category: "bilim" },
	{ id: "notron-yildizi-ne-kadar-yogundur", title: "Nötron yıldızları ne kadar yoğundur?", category: "bilim" },
	{ id: "yercekimi-dalgalari-nedir", title: "Yerçekimi dalgaları nedir?", category: "bilim" },
	{ id: "gezegenler-neden-yuvarlaktir", title: "Gezegenler neden yuvarlaktır?", category: "bilim" },
	{ id: "ay-neden-dunyaya-hep-ayni-yuzunu-gosterir", title: "Ay neden Dünya'ya hep aynı yüzünü gösterir?", category: "bilim" },
	{ id: "ay-dunyadan-uzaklasiyor-mu", title: "Ay Dünya'dan uzaklaşıyor mu?", category: "bilim" },
	{ id: "mevsimler-neden-olusur", title: "Mevsimler neden oluşur?", category: "bilim" },
	{ id: "gokyuzu-neden-mavi", title: "Gökyüzü neden mavi?", category: "bilim" },
	{ id: "gun-batimi-neden-kirmizi", title: "Gün batımı neden kırmızı?", category: "bilim" },
	{ id: "simsek-nasil-olusur", title: "Şimşek nasıl oluşur?", category: "bilim" },
	{ id: "gokgurultusu-neden-sonradan-gelir", title: "Gök gürültüsü neden şimşekten sonra gelir?", category: "bilim" },
	{ id: "ses-bosluktan-neden-gecemez", title: "Ses boşluktan neden geçemez?", category: "bilim" },
	{ id: "su-neden-donunca-genisler", title: "Su neden donunca genişler?", category: "bilim" },
	{ id: "buz-neden-suyun-ustunde-yuzer", title: "Buz neden suyun üstünde yüzer?", category: "bilim" },
	{ id: "mpemba-etkisi", title: "Sıcak su bazen neden daha hızlı donar?", category: "bilim" },
	{ id: "ates-neden-yukari-dogru-yanar", title: "Ateş neden yukarı doğru yanar?", category: "bilim" },
	{ id: "mikrodalga-firin-yemegi-nasil-isitir", title: "Mikrodalga fırın yemeği nasıl ısıtır?", category: "bilim" },
	{ id: "sabun-yagi-nasil-temizler", title: "Sabun yağı nasıl temizler?", category: "bilim" },
	{ id: "cam-kati-mi-sivi-mi", title: "Cam katı mı, sıvı mı?", category: "bilim" },

	// Teknoloji
	{ id: "gps-nasil-calisir", title: "GPS nasıl çalışır?", category: "teknoloji" },
	{ id: "internet-nasil-calisir", title: "İnternet aslında nasıl çalışır?", category: "teknoloji" },
	{ id: "wifi-nasil-calisir", title: "Wi-Fi nasıl çalışır?", category: "teknoloji" },
	{ id: "bluetooth-nasil-calisir", title: "Bluetooth nasıl çalışır?", category: "teknoloji" },
	{ id: "qr-kod-nasil-calisir", title: "QR kod nasıl çalışır?", category: "teknoloji" },
	{ id: "barkod-nasil-calisir", title: "Barkod nasıl çalışır?", category: "teknoloji" },
	{ id: "dokunmatik-ekran-parmagi-nasil-algilar", title: "Dokunmatik ekran parmağımızı nasıl algılar?", category: "teknoloji" },
	{ id: "telefon-konumumuzu-nasil-buluyor", title: "Telefon konumumuzu nasıl buluyor?", category: "teknoloji" },
	{ id: "telefon-ekrani-nasil-goruntu-olusturur", title: "Telefon ekranı görüntüyü nasıl oluşturur?", category: "teknoloji" },
	{ id: "oled-ve-lcd-farki", title: "OLED ve LCD arasındaki fark nedir?", category: "teknoloji" },
	{ id: "noise-cancelling-nasil-calisir", title: "Gürültü engelleyen kulaklıklar nasıl çalışır?", category: "teknoloji" },
	{ id: "kablosuz-sarj-nasil-calisir", title: "Kablosuz şarj nasıl çalışır?", category: "teknoloji" },
	{ id: "lityum-iyon-piller-nasil-calisir", title: "Lityum iyon piller nasıl çalışır?", category: "teknoloji" },
	{ id: "piller-neden-zamanla-bozulur", title: "Piller neden zamanla kapasite kaybeder?", category: "teknoloji" },
	{ id: "ucak-modu-ne-yapar", title: "Uçak modu aslında ne yapar?", category: "teknoloji" },
	{ id: "ucaklar-nasil-radarda-gorulur", title: "Uçaklar radarda nasıl görünür?", category: "teknoloji" },
	{ id: "radar-nasil-calisir", title: "Radar nasıl çalışır?", category: "teknoloji" },
	{ id: "sonar-nasil-calisir", title: "Sonar nasıl çalışır?", category: "teknoloji" },
	{ id: "fiber-internet-nasil-calisir", title: "Fiber internet nasıl çalışır?", category: "teknoloji" },
	{ id: "denizalti-internet-kablolari", title: "İnternet neden okyanusların altındaki kablolardan geçiyor?", category: "teknoloji" },
	{ id: "bulut-depolama-gercekte-nerede", title: "Bulut depolamadaki dosyalar gerçekte nerede?", category: "teknoloji" },
	{ id: "vpn-nasil-calisir", title: "VPN nasıl çalışır?", category: "teknoloji" },
	{ id: "https-ne-ise-yarar", title: "HTTPS neden önemlidir?", category: "teknoloji" },
	{ id: "sifreleme-nasil-calisir", title: "Dijital şifreleme nasıl çalışır?", category: "teknoloji" },
	{ id: "iki-faktorlu-dogrulama", title: "İki faktörlü doğrulama neden daha güvenlidir?", category: "teknoloji" },
	{ id: "captcha-neden-var", title: "CAPTCHA neden var?", category: "teknoloji" },
	{ id: "cookie-nedir", title: "İnternet çerezleri ne işe yarar?", category: "teknoloji" },
	{ id: "arama-motorlari-nasil-calisir", title: "Arama motorları milyarlarca sayfayı nasıl buluyor?", category: "teknoloji" },
	{ id: "google-haritalar-trafik-nasil-biliyor", title: "Harita uygulamaları trafiği nasıl biliyor?", category: "teknoloji" },
	{ id: "spotify-sarki-nasil-oneriyor", title: "Spotify hangi şarkıyı seveceğimizi nasıl tahmin ediyor?", category: "teknoloji" },
	{ id: "youtube-oneri-algoritmasi", title: "YouTube ne izleyeceğimizi nasıl tahmin ediyor?", category: "teknoloji" },
	{ id: "yapay-zeka-nasil-ogrenir", title: "Yapay zekâ nasıl öğrenir?", category: "teknoloji" },
	{ id: "llm-nasil-calisir", title: "Büyük dil modelleri nasıl çalışır?", category: "teknoloji" },
	{ id: "yapay-zeka-halusinasyonu", title: "Yapay zekâ neden olmayan şeyleri uydurur?", category: "teknoloji" },
	{ id: "yuz-tanima-nasil-calisir", title: "Yüz tanıma sistemleri nasıl çalışır?", category: "teknoloji" },
	{ id: "deepfake-nasil-yapilir", title: "Deepfake teknolojisi nasıl çalışır?", category: "teknoloji" },
	{ id: "3d-yazici-nasil-calisir", title: "3D yazıcı nasıl çalışır?", category: "teknoloji" },
	{ id: "elektrikli-arabalar-nasil-calisir", title: "Elektrikli arabalar nasıl çalışır?", category: "teknoloji" },
	{ id: "rejeneratif-frenleme", title: "Elektrikli araçlarda rejeneratif frenleme nedir?", category: "teknoloji" },
	{ id: "otonom-araclar-yolu-nasil-gorur", title: "Otonom araçlar yolu nasıl görür?", category: "teknoloji" },

	// Tarih
	{ id: "pompeii-neden-bu-kadar-iyi-korunmus-durumda", title: "Pompeii neden bu kadar iyi korunmuş durumda?", category: "tarih" },
	{ id: "roma-imparatorlugu-neden-coktu", title: "Roma İmparatorluğu neden çöktü?", category: "tarih" },
	{ id: "roma-betonu-neden-dayanikli", title: "Roma betonu neden bu kadar dayanıklı?", category: "tarih" },
	{ id: "roma-yollari-neden-unluydu", title: "Roma yolları neden bu kadar başarılıydı?", category: "tarih" },
	{ id: "antik-roma-nasil-su-tasiyordu", title: "Antik Roma milyonlarca litre suyu nasıl taşıyordu?", category: "tarih" },
	{ id: "piramitler-nasil-insa-edildi", title: "Mısır piramitleri nasıl inşa edildi?", category: "tarih" },
	{ id: "piramitler-neden-yapildi", title: "Piramitler neden yapıldı?", category: "tarih" },
	{ id: "hiyeroglifler-nasil-cozuldu", title: "Mısır hiyeroglifleri nasıl çözüldü?", category: "tarih" },
	{ id: "rossetta-tasi-neden-onemli", title: "Rosetta Taşı neden bu kadar önemli?", category: "tarih" },
	{ id: "iskenderiye-kutuphanesine-ne-oldu", title: "İskenderiye Kütüphanesi'ne ne oldu?", category: "tarih" },
	{ id: "antik-yunan-demokrasisi-nasil-calisiyordu", title: "Antik Yunan demokrasisi nasıl çalışıyordu?", category: "tarih" },
	{ id: "spartalilar-gercekte-nasil-yasiyordu", title: "Spartalılar gerçekte nasıl yaşıyordu?", category: "tarih" },
	{ id: "vikingler-gercekte-nasil-yasiyordu", title: "Vikingler gerçekte nasıl yaşıyordu?", category: "tarih" },
	{ id: "vikinglerin-boynuzlu-migferleri-var-miydi", title: "Vikinglerin gerçekten boynuzlu miğferleri var mıydı?", category: "tarih" },
	{ id: "orta-cag-gercekten-karanlik-miydi", title: "Orta Çağ gerçekten karanlık bir dönem miydi?", category: "tarih" },
	{ id: "kara-veba-avrupayi-nasil-degistirdi", title: "Kara Veba Avrupa'yı nasıl değiştirdi?", category: "tarih" },
	{ id: "ipek-yolu-neden-onemliydi", title: "İpek Yolu neden bu kadar önemliydi?", category: "tarih" },
	{ id: "mogollar-nasil-bu-kadar-buyuk-imparatorluk-kurdu", title: "Moğollar nasıl bu kadar büyük bir imparatorluk kurdu?", category: "tarih" },
	{ id: "cengiz-han-nasil-basardi", title: "Cengiz Han neden bu kadar başarılıydı?", category: "tarih" },
	{ id: "istanbulun-fethi-neden-donum-noktasi", title: "İstanbul'un fethi neden bir dönüm noktasıydı?", category: "tarih" },
	{ id: "bizans-neden-bin-yil-dayandi", title: "Bizans İmparatorluğu nasıl bin yıldan fazla ayakta kaldı?", category: "tarih" },
	{ id: "osmanli-nasil-buyudu", title: "Osmanlı İmparatorluğu nasıl bu kadar hızlı büyüdü?", category: "tarih" },
	{ id: "lale-devri-nedir", title: "Lale Devri neden bu isimle anılıyor?", category: "tarih" },
	{ id: "sanayi-devrimi-neden-ingilterede-basladi", title: "Sanayi Devrimi neden İngiltere'de başladı?", category: "tarih" },
	{ id: "fransiz-devrimi-neden-basladi", title: "Fransız Devrimi neden başladı?", category: "tarih" },
	{ id: "napolyon-nasil-yukseldi", title: "Napolyon nasıl bu kadar hızlı yükseldi?", category: "tarih" },
	{ id: "napolyon-neden-rusyayi-isgal-etti", title: "Napolyon neden Rusya'yı işgal etti?", category: "tarih" },
	{ id: "amerikan-bagimsizlik-savasi-neden-basladi", title: "Amerikan Bağımsızlık Savaşı neden başladı?", category: "tarih" },
	{ id: "birinci-dunya-savasi-neden-basladi", title: "Birinci Dünya Savaşı neden başladı?", category: "tarih" },
	{ id: "birinci-dunya-savasi-neden-siperlerde-gecdi", title: "Birinci Dünya Savaşı neden siper savaşına dönüştü?", category: "tarih" },
	{ id: "ikinci-dunya-savasi-neden-basladi", title: "İkinci Dünya Savaşı neden başladı?", category: "tarih" },
	{ id: "maginot-hatti-neden-ise-yaramadi", title: "Maginot Hattı neden işe yaramadı?", category: "tarih" },
	{ id: "d-day-neden-onemliydi", title: "Normandiya Çıkarması neden bu kadar önemliydi?", category: "tarih" },
	{ id: "soguk-savas-neden-soguk-deniyordu", title: "Soğuk Savaş'a neden 'soğuk' deniyordu?", category: "tarih" },
	{ id: "berlin-duvari-neden-yapildi", title: "Berlin Duvarı neden yapıldı?", category: "tarih" },
	{ id: "berlin-duvari-nasil-yikildi", title: "Berlin Duvarı nasıl yıkıldı?", category: "tarih" },
	{ id: "sovyetler-birligi-neden-dagildi", title: "Sovyetler Birliği neden dağıldı?", category: "tarih" },
	{ id: "kuba-fuze-krizi", title: "Küba Füze Krizi dünyayı nükleer savaşa ne kadar yaklaştırdı?", category: "tarih" },
	{ id: "titanic-neden-batti", title: "Titanic neden battı?", category: "tarih" },
	{ id: "takvimler-nasil-ortaya-cikti", title: "Takvimler nasıl ortaya çıktı?", category: "tarih" },

	// Genel kültür
	{ id: "matbaa-dunyayi-nasil-degistirdi", title: "Matbaa dünyayı nasıl değiştirdi?", category: "genel-kultur" },
	{ id: "lindy-etkisi", title: "Lindy etkisi", category: "genel-kultur" },
	{ id: "okhams-usturasi", title: "Ockham'ın usturası nedir?", category: "genel-kultur" },
	{ id: "hanlons-usturasi", title: "Hanlon'un usturası nedir?", category: "genel-kultur" },
	{ id: "cobra-etkisi", title: "Kobra etkisi nedir?", category: "genel-kultur" },
	{ id: "streisand-etkisi", title: "Streisand etkisi nedir?", category: "genel-kultur" },
	{ id: "butterfly-effect", title: "Kelebek etkisi gerçekte ne anlatır?", category: "genel-kultur" },
	{ id: "pareto-ilkesi", title: "80/20 kuralı nedir?", category: "genel-kultur" },
	{ id: "peter-ilkesi", title: "Peter ilkesi nedir?", category: "genel-kultur" },
	{ id: "murphy-kanunu", title: "Murphy Kanunu nereden çıktı?", category: "genel-kultur" },
	{ id: "goodhart-kanunu", title: "Goodhart Kanunu nedir?", category: "genel-kultur" },
	{ id: "parkinson-kanunu", title: "Parkinson Kanunu nedir?", category: "genel-kultur" },
	{ id: "dunbar-sayisi", title: "Dunbar sayısı nedir?", category: "genel-kultur" },
	{ id: "altin-oran-gercekten-ozel-mi", title: "Altın oran gerçekten doğada her yerde mi?", category: "genel-kultur" },
	{ id: "neden-hafta-yedi-gun", title: "Bir hafta neden yedi gün?", category: "genel-kultur" },
	{ id: "neden-bir-saat-60-dakika", title: "Bir saat neden 60 dakika?", category: "genel-kultur" },
	{ id: "neden-bir-dakika-60-saniye", title: "Bir dakika neden 60 saniye?", category: "genel-kultur" },
	{ id: "neden-bir-yil-12-ay", title: "Bir yıl neden 12 aya bölünmüş?", category: "genel-kultur" },
	{ id: "artik-yil-neden-var", title: "Artık yıl neden var?", category: "genel-kultur" },
	{ id: "saat-dilimleri-neden-var", title: "Saat dilimleri neden var?", category: "genel-kultur" },
	{ id: "uluslararasi-tarih-degistirme-cizgisi", title: "Uluslararası Tarih Değiştirme Çizgisi neden var?", category: "genel-kultur" },
	{ id: "klavye-neden-qwerty", title: "Klavyeler neden QWERTY düzeninde?", category: "genel-kultur" },
	{ id: "neden-trafik-isiklari-kirmizi-sari-yesil", title: "Trafik ışıkları neden kırmızı, sarı ve yeşil?", category: "genel-kultur" },
	{ id: "acil-durum-numaralari-neden-farkli", title: "Acil durum numaraları neden ülkeden ülkeye değişiyor?", category: "genel-kultur" },
	{ id: "pasaportlar-neden-farkli-renklerde", title: "Pasaportlar neden farklı renklerde?", category: "genel-kultur" },
	{ id: "ucak-pencereleri-neden-yuvarlak", title: "Uçak pencereleri neden yuvarlak?", category: "genel-kultur" },
	{ id: "ucaklarda-koltuklar-neden-dik-konuma-getirilir", title: "Uçaklarda kalkışta koltuklar neden dik konuma getirilir?", category: "genel-kultur" },
	{ id: "ucaklarda-isiklar-neden-kapatilir", title: "Uçaklarda iniş sırasında ışıklar neden kısılır?", category: "genel-kultur" },
	{ id: "otel-odalari-neden-13-numara-yok", title: "Bazı otellerde neden 13 numaralı kat yok?", category: "genel-kultur" },
	{ id: "sosyal-medya-mavi-tik", title: "Mavi tik sembolü nasıl ortaya çıktı?", category: "genel-kultur" },
	{ id: "neden-alkisliyoruz", title: "İnsanlar neden alkışlar?", category: "genel-kultur" },
	{ id: "neden-el-sikisiyoruz", title: "İnsanlar neden el sıkışır?", category: "genel-kultur" },
	{ id: "dogum-gunu-mumu-nereden-geliyor", title: "Doğum günü pastasında mum üfleme geleneği nereden geliyor?", category: "genel-kultur" },
	{ id: "nikah-yuzugu-neden-yuzuk-parmagina", title: "Nikâh yüzüğü neden yüzük parmağına takılır?", category: "genel-kultur" },
	{ id: "mezuniyet-kepleri-neden-kare", title: "Mezuniyet kepleri neden kare?", category: "genel-kultur" },

	// Psikoloji
	{ id: "diderot-etkisi", title: "Diderot etkisi", category: "psikoloji" },
	{ id: "zeigarnik-etkisi", title: "Zeigarnik etkisi", category: "psikoloji" },
	{ id: "peak-end-kurali", title: "Peak-end kuralı", category: "psikoloji" },
	{ id: "hedonik-adaptasyon", title: "Hedonik adaptasyon", category: "psikoloji" },
	{ id: "kumarbazin-yanilgisi", title: "Kumarbazın yanılgısı", category: "psikoloji" },
	{ id: "plasebo-etkisi-nasil-calisir", title: "Plasebo etkisi nasıl çalışır?", category: "psikoloji" },
	{ id: "nocebo-etkisi", title: "Nocebo etkisi nedir?", category: "psikoloji" },
	{ id: "halo-etkisi", title: "Halo etkisi nedir?", category: "psikoloji" },
	{ id: "horn-etkisi", title: "Horn etkisi nedir?", category: "psikoloji" },
	{ id: "dunning-kruger-etkisi", title: "Dunning-Kruger etkisi nedir?", category: "psikoloji" },
	{ id: "batik-maliyet-yanilgisi", title: "Batık maliyet yanılgısı nedir?", category: "psikoloji" },
	{ id: "onaylama-yanliligi", title: "Onaylama yanlılığı nedir?", category: "psikoloji" },
	{ id: "hayatta-kalma-yanliligi", title: "Hayatta kalma yanlılığı nedir?", category: "psikoloji" },
	{ id: "demirleme-etkisi", title: "Demirleme etkisi nedir?", category: "psikoloji" },
	{ id: "cerceveleme-etkisi", title: "Çerçeveleme etkisi nedir?", category: "psikoloji" },
	{ id: "sahiplik-etkisi", title: "Sahiplik etkisi nedir?", category: "psikoloji" },
	{ id: "maruz-kalma-etkisi", title: "Bir şeyi gördükçe neden daha çok severiz?", category: "psikoloji" },
	{ id: "secim-paradoksu", title: "Çok fazla seçenek neden mutsuz edebilir?", category: "psikoloji" },
	{ id: "karar-yorgunlugu", title: "Karar yorgunluğu nedir?", category: "psikoloji" },
	{ id: "analiz-felci", title: "Analiz felci nedir?", category: "psikoloji" },
	{ id: "bilissel-uyumsuzluk", title: "Bilişsel uyumsuzluk nedir?", category: "psikoloji" },
	{ id: "temel-atfetme-hatasi", title: "Temel atfetme hatası nedir?", category: "psikoloji" },
	{ id: "kendine-hizmet-eden-yanlilik", title: "Kendine hizmet eden yanlılık nedir?", category: "psikoloji" },
	{ id: "geri-bakis-yanilgisi", title: "Geriye dönüp bakınca her şey neden bariz görünür?", category: "psikoloji" },
	{ id: "kullanilabilirlik-sezgisi", title: "Aklımıza kolay gelen şeyleri neden daha olası sanırız?", category: "psikoloji" },
	{ id: "iyimserlik-yanliligi", title: "İyimserlik yanlılığı nedir?", category: "psikoloji" },
	{ id: "negatiflik-yanliligi", title: "Kötü şeyleri neden daha güçlü hatırlarız?", category: "psikoloji" },
	{ id: "recency-effect", title: "Son duyduğumuz şeyleri neden daha iyi hatırlarız?", category: "psikoloji" },
	{ id: "primacy-effect", title: "İlk öğrendiğimiz şeyleri neden daha iyi hatırlarız?", category: "psikoloji" },
	{ id: "barnum-etkisi", title: "Barnum etkisi nedir?", category: "psikoloji" },
	{ id: "pygmalion-etkisi", title: "Pygmalion etkisi nedir?", category: "psikoloji" },
	{ id: "observer-expectancy-effect", title: "Beklentiler sonucu gerçekten değiştirebilir mi?", category: "psikoloji" },
	{ id: "spotlight-etkisi", title: "Spotlight etkisi nedir?", category: "psikoloji" },
	{ id: "seyirci-etkisi", title: "Kalabalıkta insanlar neden bazen yardım etmez?", category: "psikoloji" },
	{ id: "sosyal-kanit", title: "Başkalarının yaptığı şeyi neden doğru kabul ederiz?", category: "psikoloji" },
	{ id: "suruden-gitme-etkisi", title: "Sürüden gitme etkisi nedir?", category: "psikoloji" },
	{ id: "otoriteye-itaat", title: "İnsanlar otoriteye neden bu kadar kolay itaat eder?", category: "psikoloji" },
	{ id: "stokholm-sendromu-gercek-mi", title: "Stockholm sendromu gerçekten bilimsel bir kavram mı?", category: "psikoloji" },
	{ id: "yanlis-hatira", title: "Beynimiz hiç yaşanmamış anılar üretebilir mi?", category: "psikoloji" },
	{ id: "mandela-etkisi", title: "Mandela etkisi nedir?", category: "psikoloji" },
	{ id: "deja-vu-neden-olur", title: "Déjà vu neden olur?", category: "psikoloji" },
	{ id: "jamais-vu-nedir", title: "Jamais vu nedir?", category: "psikoloji" },
	{ id: "kulakta-kalan-sarki", title: "Bir şarkı neden günlerce aklımızdan çıkmaz?", category: "psikoloji" },
	{ id: "neden-utanc-verici-anilari-hatirlariz", title: "Eski utanç verici anılar neden ansızın aklımıza gelir?", category: "psikoloji" },
	{ id: "zaman-yaslandikca-neden-hizlanir", title: "Yaşlandıkça zaman neden daha hızlı geçiyor gibi gelir?", category: "psikoloji" },
	{ id: "tatilde-zaman-neden-farkli-hissedilir", title: "Tatilde zaman neden farklı hissedilir?", category: "psikoloji" },
	{ id: "prokrastinasyon-neden-olur", title: "Neden sürekli erteleriz?", category: "psikoloji" },
	{ id: "motivasyon-neden-basladiktan-sonra-artar", title: "Bir işe başladıktan sonra motivasyon neden artar?", category: "psikoloji" },
	{ id: "uyku-oncesi-fikirler-neden-gelir", title: "En iyi fikirler neden bazen uyumadan önce gelir?", category: "psikoloji" },

	// Coğrafya
	{ id: "coller-neden-cogunlukla-belirli-enlemlerde", title: "Çöller neden çoğunlukla belirli enlemlerde?", category: "cografya" },
	{ id: "ekvator-neden-sicak", title: "Ekvator neden daha sıcak?", category: "cografya" },
	{ id: "kutuplar-neden-soguk", title: "Kutuplar neden bu kadar soğuk?", category: "cografya" },
	{ id: "daglar-nasil-olusur", title: "Dağlar nasıl oluşur?", category: "cografya" },
	{ id: "volkanlar-neden-belirli-yerlerde", title: "Volkanlar neden belirli bölgelerde yoğunlaşır?", category: "cografya" },
	{ id: "depremler-neden-belirli-yerlerde", title: "Depremler neden belirli bölgelerde daha sık olur?", category: "cografya" },
	{ id: "tektonik-levhalar-neden-hareket-eder", title: "Tektonik levhalar neden hareket eder?", category: "cografya" },
	{ id: "kitalar-hareket-ediyor-mu", title: "Kıtalar hâlâ hareket ediyor mu?", category: "cografya" },
	{ id: "pangea-nasil-parcalandi", title: "Pangea nasıl parçalandı?", category: "cografya" },
	{ id: "okyanuslar-neden-tuzlu", title: "Okyanuslar neden tuzlu?", category: "cografya" },
	{ id: "nehirler-neden-kivrimli", title: "Nehirler neden kıvrılarak akar?", category: "cografya" },
	{ id: "nehirler-neden-denize-akar", title: "Nehirler neden denize doğru akar?", category: "cografya" },
	{ id: "delta-nasil-olusur", title: "Nehir deltaları nasıl oluşur?", category: "cografya" },
	{ id: "fiyortlar-nasil-olusur", title: "Fiyortlar nasıl oluşur?", category: "cografya" },
	{ id: "adalar-nasil-olusur", title: "Adalar nasıl oluşur?", category: "cografya" },
	{ id: "mercankayaliklari-nasil-olusur", title: "Mercan adaları nasıl oluşur?", category: "cografya" },
	{ id: "sahra-neden-col-oldu", title: "Sahra nasıl çöle dönüştü?", category: "cografya" },
	{ id: "sahra-eskiden-yesil-miydi", title: "Sahra Çölü eskiden gerçekten yeşil miydi?", category: "cografya" },
	{ id: "amazon-nehri-neden-bu-kadar-buyuk", title: "Amazon Nehri neden bu kadar büyük?", category: "cografya" },
	{ id: "amazon-ormanlari-neden-onemli", title: "Amazon Ormanları neden bu kadar önemli?", category: "cografya" },
	{ id: "himalayalar-nasil-olustu", title: "Himalayalar nasıl oluştu?", category: "cografya" },
	{ id: "everest-hala-buyuyor-mu", title: "Everest hâlâ büyüyor mu?", category: "cografya" },
	{ id: "olu-deniz-neden-bu-kadar-tuzlu", title: "Ölü Deniz neden bu kadar tuzlu?", category: "cografya" },
	{ id: "karadeniz-neden-karadeniz", title: "Karadeniz'e neden Karadeniz deniyor?", category: "cografya" },
	{ id: "akdeniz-bir-gun-kurudu-mu", title: "Akdeniz bir zamanlar gerçekten kurudu mu?", category: "cografya" },
	{ id: "izlanda-neden-volkanik", title: "İzlanda neden bu kadar volkanik?", category: "cografya" },
	{ id: "norvec-neden-fiyortlarla-dolu", title: "Norveç neden fiyortlarla dolu?", category: "cografya" },
	{ id: "musonlar-nasil-olusur", title: "Muson yağmurları nasıl oluşur?", category: "cografya" },
	{ id: "kasirga-nasil-olusur", title: "Kasırgalar nasıl oluşur?", category: "cografya" },
	{ id: "hortum-nasil-olusur", title: "Hortumlar nasıl oluşur?", category: "cografya" },

	// Sanat
	{ id: "perspektif-resmi-nasil-degistirdi", title: "Perspektif resmi nasıl değiştirdi?", category: "sanat" },
	{ id: "ronesans-neden-italyada-basladi", title: "Rönesans neden İtalya'da başladı?", category: "sanat" },
	{ id: "mona-lisa-neden-unlu", title: "Mona Lisa neden bu kadar ünlü?", category: "sanat" },
	{ id: "mona-lisanin-gozleri-neden-takip-ediyor", title: "Mona Lisa'nın gözleri bizi gerçekten takip ediyor mu?", category: "sanat" },
	{ id: "van-gogh-neden-hayattayken-unlu-degildi", title: "Van Gogh neden hayattayken ünlü değildi?", category: "sanat" },
	{ id: "yildizli-gece-neden-bu-kadar-unlu", title: "Yıldızlı Gece neden bu kadar etkileyici?", category: "sanat" },
	{ id: "picasso-neden-yuzleri-bozuk-cizdi", title: "Picasso yüzleri neden parçalara ayırarak çizdi?", category: "sanat" },
	{ id: "kubizm-nedir", title: "Kübizm neyi değiştirdi?", category: "sanat" },
	{ id: "empresyonizm-nasil-ortaya-cikti", title: "Empresyonizm nasıl ortaya çıktı?", category: "sanat" },
	{ id: "fotograf-resim-sanatini-nasil-degistirdi", title: "Fotoğrafın icadı resim sanatını nasıl değiştirdi?", category: "sanat" },
	{ id: "grafiti-ne-zaman-sanat-oldu", title: "Grafiti ne zaman sanat kabul edilmeye başladı?", category: "sanat" },
	{ id: "banksy-kim", title: "Banksy'nin kimliği neden hâlâ bilinmiyor?", category: "sanat" },
	{ id: "modern-sanat-neden-pahali", title: "Modern sanat eserleri neden bu kadar pahalı olabilir?", category: "sanat" },
	{ id: "sanat-eserinin-degerini-ne-belirler", title: "Bir sanat eserinin değerini ne belirler?", category: "sanat" },
	{ id: "muzik-neden-duygu-yaratir", title: "Müzik neden güçlü duygular yaratır?", category: "sanat" },
	{ id: "minor-akorlar-neden-huzunlu", title: "Minör akorlar neden hüzünlü gelir?", category: "sanat" },
	{ id: "muzikte-nakarat-neden-akilda-kalir", title: "Nakaratlar neden bu kadar kolay akılda kalır?", category: "sanat" },
	{ id: "senfoni-nedir", title: "Senfoni nedir?", category: "sanat" },
	{ id: "opera-nasil-ortaya-cikti", title: "Opera nasıl ortaya çıktı?", category: "sanat" },
	{ id: "caz-nasil-dogdu", title: "Caz müzik nasıl doğdu?", category: "sanat" },

	// Ekonomi
	{ id: "bir-ulkenin-para-birimi-neden-deger-kaybeder", title: "Bir ülkenin para birimi neden değer kaybeder?", category: "ekonomi" },
	{ id: "enflasyon-nedir", title: "Enflasyon neden oluşur?", category: "ekonomi" },
	{ id: "hiperenflasyon-nasil-olusur", title: "Hiperenflasyon nasıl oluşur?", category: "ekonomi" },
	{ id: "faiz-artarsa-ne-olur", title: "Faiz artınca ekonomide ne olur?", category: "ekonomi" },
	{ id: "faiz-duserse-ne-olur", title: "Faiz düşünce ekonomide ne olur?", category: "ekonomi" },
	{ id: "merkez-bankasi-ne-yapar", title: "Merkez bankaları ne yapar?", category: "ekonomi" },
	{ id: "merkez-bankalari-neden-bagimsiz", title: "Merkez bankalarının bağımsız olması neden önemlidir?", category: "ekonomi" },
	{ id: "para-nasil-yaratilir", title: "Bankalar nasıl para yaratır?", category: "ekonomi" },
	{ id: "bankalar-nasil-para-kazanir", title: "Bankalar nasıl para kazanır?", category: "ekonomi" },
	{ id: "bank-run-nedir", title: "Bank run nedir?", category: "ekonomi" },
	{ id: "borsa-neden-yukselir", title: "Borsa neden yükselir?", category: "ekonomi" },
	{ id: "borsa-neden-duser", title: "Borsa neden aniden düşer?", category: "ekonomi" },
	{ id: "hisse-fiyati-nasil-belirlenir", title: "Bir hissenin fiyatı nasıl belirlenir?", category: "ekonomi" },
	{ id: "balon-ekonomisi-nedir", title: "Ekonomik balon nasıl oluşur?", category: "ekonomi" },
	{ id: "lale-cilginligi", title: "Lale Çılgınlığı gerçekten tarihin ilk ekonomik balonu muydu?", category: "ekonomi" },
	{ id: "2008-krizi-neden-oldu", title: "2008 finansal krizi neden oldu?", category: "ekonomi" },
	{ id: "1929-buyuk-buhran-neden-oldu", title: "1929 Büyük Buhranı neden oldu?", category: "ekonomi" },
	{ id: "resesyon-nedir", title: "Resesyon nedir?", category: "ekonomi" },
	{ id: "stagflasyon-nedir", title: "Stagflasyon nedir?", category: "ekonomi" },
	{ id: "gsmh-ve-gsyh-farki", title: "GSYH aslında neyi ölçer?", category: "ekonomi" },
	{ id: "issizlik-orani-nasil-hesaplanir", title: "İşsizlik oranı nasıl hesaplanır?", category: "ekonomi" },
	{ id: "asgari-ucret-artarsa-ne-olur", title: "Asgari ücret artınca ekonomide ne olur?", category: "ekonomi" },
	{ id: "vergi-neden-var", title: "Vergiler neden var?", category: "ekonomi" },
	{ id: "artan-oranli-vergi-nedir", title: "Artan oranlı vergi sistemi nasıl çalışır?", category: "ekonomi" },
	{ id: "devletler-neden-borclanir", title: "Devletler neden borçlanır?", category: "ekonomi" },
	{ id: "devletler-kime-borclu", title: "Devletler aslında kime borçlu?", category: "ekonomi" },
	{ id: "ulke-iflas-eder-mi", title: "Bir ülke iflas edebilir mi?", category: "ekonomi" },
	{ id: "altin-neden-degerli", title: "Altın neden binlerce yıldır değerli?", category: "ekonomi" },
	{ id: "dolar-neden-rezerv-para", title: "Dolar neden dünyanın rezerv parası?", category: "ekonomi" },
	{ id: "bitcoin-neden-degerli", title: "Bitcoin neden değerli kabul ediliyor?", category: "ekonomi" },
	{ id: "bitcoin-arzi-neden-sinirli", title: "Bitcoin'in arzı neden 21 milyonla sınırlı?", category: "ekonomi" },
	{ id: "arz-talep-nasil-calisir", title: "Arz ve talep fiyatları nasıl belirler?", category: "ekonomi" },
	{ id: "fiyatlar-neden-99-ile-biter", title: "Fiyatlar neden 9,99 ile biter?", category: "ekonomi" },
	{ id: "ucak-biletleri-neden-surekli-degisir", title: "Uçak bileti fiyatları neden sürekli değişir?", category: "ekonomi" },
	{ id: "oteller-fiyatlari-nasil-belirler", title: "Oteller oda fiyatlarını nasıl belirler?", category: "ekonomi" },

	// Doğa
	{ id: "ahtapotlarin-neden-uc-kalbi-vardir", title: "Ahtapotların neden üç kalbi vardır?", category: "doga" },
	{ id: "ahtapotlar-neden-renk-degistirir", title: "Ahtapotlar nasıl renk değiştirir?", category: "doga" },
	{ id: "ahtapotlar-neden-bu-kadar-zeki", title: "Ahtapotlar neden bu kadar zekidir?", category: "doga" },
	{ id: "bukalemunlar-neden-renk-degistirir", title: "Bukalemunlar gerçekten kamuflaj için mi renk değiştirir?", category: "doga" },
	{ id: "flamingolar-neden-pembe", title: "Flamingolar neden pembe?", category: "doga" },
	{ id: "zebralar-neden-cizgili", title: "Zebraların neden çizgileri var?", category: "doga" },
	{ id: "kaplanlarin-derisi-de-cizgili-mi", title: "Kaplanların derisi de çizgili mi?", category: "doga" },
	{ id: "kutup-ayilari-gercekten-beyaz-mi", title: "Kutup ayılarının tüyleri gerçekten beyaz mı?", category: "doga" },
	{ id: "penguenler-neden-ucamaz", title: "Penguenler neden uçamaz?", category: "doga" },
	{ id: "devekusu-neden-ucamaz", title: "Devekuşları neden uçamaz?", category: "doga" },
	{ id: "kuslar-nasil-yon-bulur", title: "Göçmen kuşlar yollarını nasıl bulur?", category: "doga" },
	{ id: "guvercinler-evi-nasil-bulur", title: "Güvercinler evlerini nasıl bulur?", category: "doga" },
	{ id: "kediler-neden-mirildanir", title: "Kediler neden mırıldanır?", category: "doga" },
	{ id: "kediler-neden-ayaklarinin-ustune-duser", title: "Kediler neden çoğunlukla ayaklarının üstüne düşer?", category: "doga" },
	{ id: "kediler-neden-kutu-sever", title: "Kediler neden kutuları bu kadar sever?", category: "doga" },
	{ id: "kopekler-neden-kuyruk-sallar", title: "Köpekler neden kuyruk sallar?", category: "doga" },
	{ id: "kopekler-neden-koku-almada-iyi", title: "Köpekler neden bu kadar iyi koku alır?", category: "doga" },
	{ id: "filler-gercekten-unutmaz-mi", title: "Filler gerçekten hiçbir şeyi unutmaz mı?", category: "doga" },
	{ id: "yunuslar-ne-kadar-zeki", title: "Yunuslar ne kadar zekidir?", category: "doga" },
	{ id: "yunuslar-nasil-uyur", title: "Yunuslar boğulmadan nasıl uyur?", category: "doga" },
	{ id: "balinalar-neden-sarki-soyler", title: "Balinalar neden şarkı söyler?", category: "doga" },
	{ id: "balinalar-nasil-bu-kadar-buyudu", title: "Balinalar nasıl bu kadar büyük oldu?", category: "doga" },
	{ id: "kopekbaliklari-kan-kokusunu-ne-kadar-uzaktan-alir", title: "Köpekbalıkları kan kokusunu gerçekten kilometrelerce öteden alabilir mi?", category: "doga" },
	{ id: "kopekbaliklari-neden-surekli-yuzer", title: "Bazı köpekbalıkları neden sürekli yüzmek zorunda?", category: "doga" },
	{ id: "denizanalarinin-beyni-var-mi", title: "Denizanalarının beyni var mı?", category: "doga" },
	{ id: "denizanasi-nasil-hareket-eder", title: "Denizanaları beyinleri olmadan nasıl hareket eder?", category: "doga" },
	{ id: "karincalar-nasil-organize-olur", title: "Karıncalar lider olmadan nasıl organize olur?", category: "doga" },
	{ id: "karincalar-nasil-yol-bulur", title: "Karıncalar yollarını nasıl bulur?", category: "doga" },
	{ id: "arilar-nasil-iletisim-kurar", title: "Arılar dans ederek nasıl iletişim kurar?", category: "doga" },
	{ id: "arilar-neden-altigen-petek-yapar", title: "Arılar neden altıgen petek yapar?", category: "doga" },
	{ id: "arilar-yok-olursa-ne-olur", title: "Arılar yok olursa ne olur?", category: "doga" },
	{ id: "orumcekler-kendi-agina-neden-yapismaz", title: "Örümcekler kendi ağlarına neden yapışmaz?", category: "doga" },
	{ id: "orumcek-agi-neden-guclu", title: "Örümcek ağı neden bu kadar güçlü?", category: "doga" },
	{ id: "atesbocekleri-nasil-isik-uretir", title: "Ateş böcekleri nasıl ışık üretir?", category: "doga" },
	{ id: "kelebekler-nasil-donusur", title: "Tırtıl kelebeğe nasıl dönüşür?", category: "doga" },
	{ id: "aksotl-neden-uzuv-yeniler", title: "Aksolotllar kaybettikleri uzuvları nasıl yeniler?", category: "doga" },
	{ id: "kertenkele-kuyrugunu-nasil-yeniler", title: "Kertenkele kuyruğunu nasıl yeniden çıkarır?", category: "doga" },
	{ id: "tardigradlar-neden-dayanikli", title: "Tardigradlar neden bu kadar dayanıklı?", category: "doga" },
	{ id: "agaclar-birbiriyle-iletisim-kurabilir-mi", title: "Ağaçlar birbirleriyle iletişim kurabilir mi?", category: "doga" },
	{ id: "bitkiler-isiga-nasil-doner", title: "Bitkiler ışığın yönünü nasıl bilir?", category: "doga" },
	{ id: "etobur-bitkiler-neden-bocek-yer", title: "Etobur bitkiler neden böcek yer?", category: "doga" },
	{ id: "venus-sinek-kapani-nasil-sayar", title: "Venüs sinekkapanı dokunuşları nasıl sayar?", category: "doga" },
	{ id: "mantarlar-bitki-mi", title: "Mantarlar neden bitki değildir?", category: "doga" },
	{ id: "mantar-aglari-nedir", title: "Ormanların altındaki mantar ağları nedir?", category: "doga" },
	{ id: "yapraklar-sonbaharda-neden-renk-degistirir", title: "Yapraklar sonbaharda neden renk değiştirir?", category: "doga" },

	// Mitoloji
	{ id: "prometheus-neden-insanlara-atesi-verdi", title: "Prometheus neden insanlara ateşi verdi?", category: "mitoloji" },
	{ id: "pandoranin-kutusu", title: "Pandora'nın kutusu hikâyesi ne anlatır?", category: "mitoloji" },
	{ id: "sisifosun-cezasi", title: "Sisifos neden sonsuza kadar kaya taşımaya mahkûm edildi?", category: "mitoloji" },
	{ id: "narkissos-hikayesi", title: "Narkissos neden kendi yansımasına âşık oldu?", category: "mitoloji" },
	{ id: "ikarus-neden-dustu", title: "İkarus neden gökyüzünden düştü?", category: "mitoloji" },
	{ id: "medusa-neden-canavara-donustu", title: "Medusa nasıl bir canavara dönüştü?", category: "mitoloji" },
	{ id: "minotor-labirenti", title: "Minotor neden bir labirentte tutuluyordu?", category: "mitoloji" },
	{ id: "truva-ati-hikayesi", title: "Truva Atı hikâyesi gerçekten yaşandı mı?", category: "mitoloji" },
	{ id: "akhilleusun-topugu", title: "Akhilleus'un topuğu hikâyesi nereden geliyor?", category: "mitoloji" },
	{ id: "odysseus-neden-on-yil-donemedi", title: "Odysseus neden evine on yılda dönebildi?", category: "mitoloji" },
	{ id: "midas-dokunusu", title: "Kral Midas'ın dokunduğu her şey neden altına dönüşüyordu?", category: "mitoloji" },
	{ id: "orfeus-ve-eurydike", title: "Orfeus neden arkasına bakmamalıydı?", category: "mitoloji" },
	{ id: "atlas-dunyayi-mi-tasiyordu", title: "Atlas gerçekten Dünya'yı mı taşıyordu?", category: "mitoloji" },
	{ id: "cerberus-neden-uc-basli", title: "Kerberos neden üç başlıydı?", category: "mitoloji" },
	{ id: "hades-kotu-bir-tanri-miydi", title: "Hades gerçekten kötü bir tanrı mıydı?", category: "mitoloji" },
	{ id: "zeus-nasil-tanrilarin-krali-oldu", title: "Zeus nasıl tanrıların kralı oldu?", category: "mitoloji" },
	{ id: "kronos-neden-cocuklarini-yuttu", title: "Kronos neden çocuklarını yuttu?", category: "mitoloji" },
	{ id: "thorun-cekici-neden-ozel", title: "Thor'un çekici Mjölnir neden özeldi?", category: "mitoloji" },
	{ id: "loki-neden-bu-kadar-onemli", title: "Loki İskandinav mitolojisinde neden bu kadar önemli?", category: "mitoloji" },
	{ id: "ragnarok-nedir", title: "Ragnarök nedir?", category: "mitoloji" },
	{ id: "valhalla-nedir", title: "Valhalla'ya kimler gidebilirdi?", category: "mitoloji" },
	{ id: "odin-neden-tek-gozlu", title: "Odin neden tek gözlü?", category: "mitoloji" },
	{ id: "yggdrasil-nedir", title: "Yggdrasil nedir?", category: "mitoloji" },
	{ id: "anubis-neden-cakal-basli", title: "Anubis neden çakal başlı tasvir edilir?", category: "mitoloji" },
	{ id: "osiris-hikayesi", title: "Osiris'in parçalanması hikâyesi ne anlatır?", category: "mitoloji" },
	{ id: "ra-her-gece-nereye-gidiyordu", title: "Ra her gece nereye gidiyordu?", category: "mitoloji" },
	{ id: "feniks-neden-kullerinden-dogar", title: "Anka kuşu neden küllerinden yeniden doğar?", category: "mitoloji" },
	{ id: "ejderhalar-neden-bircok-kulturde-var", title: "Ejderhalar neden birbirinden uzak kültürlerde ortaya çıktı?", category: "mitoloji" },
	{ id: "tek-boynuzlu-at-efsanesi", title: "Tek boynuzlu at efsanesi nasıl ortaya çıktı?", category: "mitoloji" },
	{ id: "denizkizi-efsaneleri", title: "Denizkızı efsaneleri nasıl ortaya çıktı?", category: "mitoloji" },
];